


export const items = [
    // 🔹 MOBILES
  {
    id: 22,
    category: "mobiles",
    title: "OnePlus 12",
    imgSrc: "https://m.media-amazon.com/images/I/71V--WZVUIL._AC_UY218_.jpg",
    amazonLink: "#",
    description: "OnePlus 12 5G | Snapdragon 8 Gen 3 | 12GB RAM, 256GB Storage",
    price: "64999",
  },
  {
    id: 23,
    category: "mobiles",
    title: "Google Pixel 8 Pro",
    imgSrc: 'https://in.static.webuy.com/product_images/Phones/Phones%20Android/SGOOPIX8P256GBUNLB_l.jpg',
    amazonLink: "#",
    description: "Google Pixel 8 Pro | AI Camera | Pure Android Experience",
    price: "106999",
  },
  {
    id: 24,
    category: "mobiles",
    title: "Samsung Galaxy A55",
    imgSrc: "https://m.media-amazon.com/images/I/41cXVuSDFvL._SY300_SX300_QL70_FMwebp_.jpg",
    amazonLink: "#",
    description: "Samsung Galaxy A55 5G | AMOLED Display | 5000mAh Battery",
    price: "39999",
  },

  // 🔹 LAPTOPS
  {
    id: 25,
    category: "laptops",
    title: "HP Pavilion 14",
    imgSrc: "https://m.media-amazon.com/images/I/71TPda7cwUL._AC_UY218_.jpg",
    amazonLink: "#",
    description: "HP Pavilion 14 | Intel i5 12th Gen | 16GB RAM | SSD",
    price: "67990",
  },
  {
    id: 26,
    category: "laptops",
    title: "ASUS ROG Strix G15",
    imgSrc: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSDD_ALDTpyN6p5cqJtNHpgJuXg_Ctrk4j-t9eSGeuaslMnzvwm3MuMMsD6ysSVM2rzmJnb3dvwmb3aRpCECbaw3rUWb_S1SO_Lp91vdUEUAMjpnW0bnfs-wdPqC4hPZJc8FmpLk1PQ4Ik&usqp=CAc",
    amazonLink: "#",
    description: "ASUS ROG Strix G15 Gaming Laptop | Ryzen 7 | RTX 3060",
    price: "119990",
  },
  {
    id: 27,
    category: "laptops",
    title: "Dell XPS 13",
    imgSrc: "https://m.media-amazon.com/images/I/71duqJdFGOL._AC_UY218_.jpg",
    amazonLink: "#",
    description: "Dell XPS 13 | Premium Ultrabook | InfinityEdge Display",
    price: "134990",
  },

  // 🔹 TABLETS
  {
    id: 28,
    category: "tablets",
    title: "iPad Air M1",
    imgSrc: "https://m.media-amazon.com/images/I/61XZQXFQeVL._AC_UY218_.jpg",
    amazonLink: "#",
    description: "Apple iPad Air with M1 chip | 10.9-inch Liquid Retina",
    price: "59900",
  },
  {
    id: 29,
    category: "tablets",
    title: "Samsung Galaxy Tab S9",
    imgSrc: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQzYvQD16ZzwgchcfcdyKRtRUzNaKA4jvVqEG8i-YkwN9ZqUtl0gKxOOxpMl7nxg6qFJswV0R3RAK9Xy7iPRPkhb-bU2TmGdXZUHSAFUFmnCuP8ArF_q2w0Sq0zFqka_vzV&usqp=CAc",
    amazonLink: "#",
    description: "Samsung Galaxy Tab S9 | AMOLED | Snapdragon 8 Gen 2",
    price: "74999",
  },
  {
    id: 30,
    category: "tablets",
    title: "Realme Pad X",
    imgSrc: "https://m.media-amazon.com/images/I/61OduK+OwBL._AC_UF1000,1000_QL80_.jpg",
    amazonLink: "#",
    description: "Realme Pad X | Snapdragon 695 | 5G Tablet",
    price: "24999",
  },

  // 🔹 WATCHES
  {
    id: 31,
    category: "watches",
    title: "Samsung Galaxy Watch 6",
    imgSrc: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSWGbeXPzA4jiSYv7DbxoMgVdQyZ_T42CCZpBKFqFWi4j_hkQ-Hi5gENw4THhQ08ol4tDDAjLCd5bT1gv1nwMtJsdBi2FYFOay3pqHcCnmQr7cC6_EnbPGUcwY9FLmHCdhF&usqp=CAc",
    amazonLink: "#",
    description: "Samsung Galaxy Watch 6 | AMOLED | Health Tracking",
    price: "32999",
  },
  {
    id: 32,
    category: "watches",
    title: "Noise ColorFit Ultra 3",
    imgSrc: "https://images-eu.ssl-images-amazon.com/images/I/61lKe3Lp68L._AC_UL210_SR210,210_.jpg",
    amazonLink: "#",
    description: "Noise ColorFit Ultra 3 | AMOLED Display | BT Calling",
    price: "4999",
  },
  {
    id: 33,
    category: "watches",
    title: "Fire-Boltt Visionary",
    imgSrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR11OFw1LW3zp2HOILLUtPFlWSE0dut0CaYmA&s",
    amazonLink: "#",
    description: "Fire-Boltt Visionary | Stainless Steel | AMOLED",
    price: "3799",
  },

  {
    id: 1,
    category: "mobiles",
    title: "Apple iPhone 14",
    // imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    imgSrc: "https://m.media-amazon.com/images/I/713SsA7gftL._AC_UY218_.jpg",
    amazonLink: "https://amzn.to/3PuckZp",
    description: "Apple iPhone 14 (128 GB) - Blue",
    price: "89999",
  },
  {
    id: 5,
    category: "laptops",
    title: "Xiaomi Notebookpro",
    imgSrc: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3EzeQaC",
    description: "Xiaomi [Smartchoice] Notebookpro ",
    price: "49999",
  },
  {
    id: 7,
    category: "tablets",
    title: "Xiaomi Pad 6",
    imgSrc: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
    amazonLink: "https://amzn.to/3ZeNRdY",
    description: "Xiaomi Pad 6| Qualcomm Snapdragon 870| ",
    price: "29999",
  },
  {
    id: 2,
    category: "mobiles",
    title: "Apple iPhone 11",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    amazonLink: "https://amzn.to/44MiYi6",
    description: "Apple iPhone 11 (64GB) - White",
    price: "79999",
  },
  {
    id: 6,
    category: "tablets",
    title: "Lenovo Tab P12 Pro AMOLED",
    imgSrc: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
    amazonLink: "https://amzn.to/3RabsdH",
    description:
      "Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only), Storm Grey with Precision Pen 3",
    price: "19999",
  },
  {
    id: 3,
    category: "mobiles",
    title: "Apple iPhone 13",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3r6XJtv",
    description: "Apple iPhone 13 (128GB) - Blue",
    price: "69999",
  },
  {
    id: 4,
    category: "laptops",
    title: "Lenovo IdeaPad Slim 5 ",
    imgSrc: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
    amazonLink: "https://amzn.to/44JsK4r",
    description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm) ',
    price: "29999",
  },
  {
    id: 9,
    category: "tablets",
    title: "Samsung Galaxy Tab A8",
    imgSrc: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
    amazonLink: "https://amzn.to/3Pdsh4F",
    description:
      "Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)",
    price: "49999",
  },
  {
    id: 8,
    category: "laptops",
    title: "Apple MacBook Air Laptop",
    imgSrc: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3r9rvhm",
    description:
      "Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ",
    price: "89999",
  },
  {
    id: 10,
    category: "mobiles",
    title: "iPhone 16",
    imgSrc: "https://m.media-amazon.com/images/I/713SsA7gftL._AC_UY218_.jpg",
    amazonLink: "#",
    description:
      "iPhone 16 128 GB: 5G Mobile Phone with Camera Control, A18 Chip and a Big Boost in Battery Life. Works with AirPods; Ultramarine",
    price: "72900",
  },
  {
    id: 11,
    category: "mobiles",
    title: "iPhone 16 (Pink)",
    imgSrc: "https://m.media-amazon.com/images/I/713SsA7gftL._AC_UY218_.jpg",
    amazonLink: "#",
    description:
      "iPhone 16 128 GB: 5G Mobile Phone with Camera Control, A18 Chip and a Big Boost in Battery Life. Works with AirPods; Pink",
    price: "73400",
  },
  {
    id: 12,
    category: "mobiles",
    title: "iPhone 16 (256GB)",
    imgSrc: "https://m.media-amazon.com/images/I/713SsA7gftL._AC_UY218_.jpg",
    amazonLink: "#",
    description:
      "iPhone 16 256 GB: 5G Mobile Phone with Camera Control, A18 Chip and a Big Boost in Battery Life. Works with AirPods; Ultramarine",
    price: "83400",
  },
  {
    id: 13,
    category: "mobiles",
    title: "Samsung Galaxy S25 Ultra",
    imgSrc: "https://m.media-amazon.com/images/I/71uqj6BKnRL._AC_UY218_.jpg",
    amazonLink: "#",
    description:
      "Samsung Galaxy S25 Ultra 5G AI Smartphone (Titanium Black, 12GB RAM, 256GB Storage), 200MP Camera, S Pen Included, Long Battery Life",
    price: "129999",
  },
  {
    id: 14,
    category: "mobiles",
    title: "Samsung Galaxy S23 Ultra",
    imgSrc: "https://m.media-amazon.com/images/I/71lD7eGdW-L._AC_UY218_.jpg",
    amazonLink: "#",
    description:
      "Samsung Galaxy S23 Ultra 5G AI Smartphone (Green, 12GB, 256GB Storage)",
    price: "84000",
  },
  {
    id: 15,
    category: "laptops",
    title: "MacBook Air M2",
    imgSrc: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._AC_UY218_.jpg",
    amazonLink: "#",
    description: "MacBook Air with M2 chip",
    price: "76990",
  },
  {
    id: 16,
    category: "laptops",
    title: "MacBook Air 15",
    imgSrc: "https://m.media-amazon.com/images/I/71duqJdFGOL._AC_UY218_.jpg",
    amazonLink: "#",
    description: "MacBook Air 15-inch, powerful and lightweight",
    price: "167990",
  },
  {
    id: 17,
    category: "laptops",
    title: "MacBook Air 2022",
    imgSrc: "https://m.media-amazon.com/images/I/71duqJdFGOL._AC_UY218_.jpg",
    amazonLink: "#",
    description: "MacBook Air 2022 edition, sleek and efficient",
    price: "89990",
  },
  {
    id: 18,
    category: "laptops",
    title: "MacBook Pro 2024",
    imgSrc: "https://m.media-amazon.com/images/I/613+7m34z2L._AC_UY218_.jpg",
    amazonLink: "#",
    description: "MacBook Pro 2024, ultimate performance for professionals",
    price: "279990",
  },
  {
    id: 19,
    category: "watches",
    title: "Apple Watch SE",
    imgSrc: "https://m.media-amazon.com/images/I/61T4-3BedZL._AC_UL320_.jpg",
    amazonLink: "#",
    description: "Apple Watch SE 2024, ultimate performance for professionals",
    price: "59990",
  },
  {
    id: 20,
    category: "watches",
    title: "Apple Watch Ultra",
    imgSrc: "https://m.media-amazon.com/images/I/61DEUVd9PwL._AC_UL320_.jpg",
    amazonLink: "#",
    description: "Apple Watch SE 2024, ultimate performance for professionals",
    price: "39990",
  },
  {
    id: 21,
    category: "watches",
    title: "Apple Watch Series - 9",
    imgSrc: "https://m.media-amazon.com/images/I/71xQgYQZ5FL._AC_UL320_.jpg",
    amazonLink: "#",
    description: "Apple Watch SE 2024, ultimate performance for professionals",
    price: "29990",
  },
];


export const Videos = [
  {
    category: "mobiles",
    name: "iPhone",
    url: "https://www.apple.com/105/media/ww/iphone/family/2025/e7ff365a-cb59-4ce9-9cdf-4cb965455b69/anim/welcome3/large.mp4",
  },
  {
    category: "laptops",
    name: "MacBook",
    url: "https://www.apple.com/105/media/us/mac/family/2025/59856fc1-d007-421a-90ee-734ddf3fd25d/anim/welcome/large.mp4",
  },
  {
    category: "tablets",
    name: "iPad",
    url: "https://www.apple.com/assets-www/en_WW/ipad/welcome/04854789d_large.mp4",
  },
  {
    category: "watches",
    name: "Apple Watch",
    url: "https://www.apple.com/105/media/ww/watch/2024/f0b51c31-e8a5-44d7-b23d-51bd2858454a/anim/hero/large.mp4",
  },
  {
    category: "tv & entertainment",
    name: "Apple TV & Entertainment",
    url: "https://www.apple.com/105/media/us/services/2024/a8e4c2f2-5eaa-476d-b419-e6faf9237070/anim/sizzle/large.mp4",
  },
    {
    id: 22,
    category: "mobiles",
    title: "OnePlus 12",
    imgSrc: "https://m.media-amazon.com/images/I/71V--WZVUIL._AC_UY218_.jpg",
    amazonLink: "#",
    description: "OnePlus 12 5G | Snapdragon 8 Gen 3 | 12GB RAM, 256GB Storage",
    price: "64999",
  },
  {
    id: 23,
    category: "mobiles",
    title: "Google Pixel 8 Pro",
    imgSrc: "https://m.media-amazon.com/images/I/61z3m7vJ8XL._AC_UY218_.jpg",
    amazonLink: "#",
    description: "Google Pixel 8 Pro | AI Camera | Pure Android Experience",
    price: "106999",
  },
  {
    id: 24,
    category: "mobiles",
    title: "Samsung Galaxy A55",
    imgSrc: "https://m.media-amazon.com/images/I/71KJ6y2P4-L._AC_UY218_.jpg",
    amazonLink: "#",
    description: "Samsung Galaxy A55 5G | AMOLED Display | 5000mAh Battery",
    price: "39999",
  },

  // 🔹 LAPTOPS
  {
    id: 25,
    category: "laptops",
    title: "HP Pavilion 14",
    imgSrc: "https://m.media-amazon.com/images/I/71TPda7cwUL._AC_UY218_.jpg",
    amazonLink: "#",
    description: "HP Pavilion 14 | Intel i5 12th Gen | 16GB RAM | SSD",
    price: "67990",
  },
  {
    id: 26,
    category: "laptops",
    title: "ASUS ROG Strix G15",
    imgSrc: "https://m.media-amazon.com/images/I/81lIErPp6NL._AC_UY218_.jpg",
    amazonLink: "#",
    description: "ASUS ROG Strix G15 Gaming Laptop | Ryzen 7 | RTX 3060",
    price: "119990",
  },
  {
    id: 27,
    category: "laptops",
    title: "Dell XPS 13",
    imgSrc: "https://m.media-amazon.com/images/I/71duqJdFGOL._AC_UY218_.jpg",
    amazonLink: "#",
    description: "Dell XPS 13 | Premium Ultrabook | InfinityEdge Display",
    price: "134990",
  },

  // 🔹 TABLETS
  {
    id: 28,
    category: "tablets",
    title: "iPad Air M1",
    imgSrc: "https://m.media-amazon.com/images/I/61XZQXFQeVL._AC_UY218_.jpg",
    amazonLink: "#",
    description: "Apple iPad Air with M1 chip | 10.9-inch Liquid Retina",
    price: "59900",
  },
  {
    id: 29,
    category: "tablets",
    title: "Samsung Galaxy Tab S9",
    imgSrc: "https://m.media-amazon.com/images/I/61yJt8QbZML._AC_UY218_.jpg",
    amazonLink: "#",
    description: "Samsung Galaxy Tab S9 | AMOLED | Snapdragon 8 Gen 2",
    price: "74999",
  },
  {
    id: 30,
    category: "tablets",
    title: "Realme Pad X",
    imgSrc: "https://m.media-amazon.com/images/I/71v6N9b8mKL._AC_UY218_.jpg",
    amazonLink: "#",
    description: "Realme Pad X | Snapdragon 695 | 5G Tablet",
    price: "24999",
  },

  // 🔹 WATCHES
  {
    id: 31,
    category: "watches",
    title: "Samsung Galaxy Watch 6",
    imgSrc: "https://m.media-amazon.com/images/I/61Dk4gI5kML._AC_UL320_.jpg",
    amazonLink: "#",
    description: "Samsung Galaxy Watch 6 | AMOLED | Health Tracking",
    price: "32999",
  },
  {
    id: 32,
    category: "watches",
    title: "Noise ColorFit Ultra 3",
    imgSrc: "https://m.media-amazon.com/images/I/61dZ3pH-9RL._AC_UL320_.jpg",
    amazonLink: "#",
    description: "Noise ColorFit Ultra 3 | AMOLED Display | BT Calling",
    price: "4999",
  },
  {
    id: 33,
    category: "watches",
    title: "Fire-Boltt Visionary",
    imgSrc: "https://m.media-amazon.com/images/I/61lI8kJpSIL._AC_UL320_.jpg",
    amazonLink: "#",
    description: "Fire-Boltt Visionary | Stainless Steel | AMOLED",
    price: "3799",
  },


];


export const trendingProducts = [
  {
    name: "iPhone 15 Pro",
    image: "https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg",
  },
  {
    name: "iPad Pro",
    image: "https://m.media-amazon.com/images/I/61apfl6EiqL._AC_UL320_.jpg",
  },
  {
    name: "iPhone 15 Pro",
    image: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
  },
  {
    name: "MacBook Pro",
    image: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
  },
  {
    name: "iPhone 15 Pro",
    image: "https://m.media-amazon.com/images/I/71Lcaat+UUL._AC_UY218_.jpg",
  },
  {
    name: "MacBook Pro",
    image: "https://m.media-amazon.com/images/I/71xQgYQZ5FL._AC_UL320_.jpg",
  },
  {
    name: "iPad Pro",
    image: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
  },
  {
    name: "AirPods Pro",
    image: "https://m.media-amazon.com/images/I/61T4-3BedZL._AC_UL320_.jpg",
  },
  {
    name: "Apple Watch Series 9",
    image: "https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg",
  },
  {
    name: "Apple Watch Series 9",
    image: "https://m.media-amazon.com/images/I/61DEUVd9PwL._AC_UL320_.jpg",
  },
  {
    name: "Apple Watch Series 9",
    image: "https://m.media-amazon.com/images/I/61uA2UVnYWL._AC_UY218_.jpg",
  },
];